### PR TITLE
create SDL_Qt_HMI Project , including HMIFrameWoek framework, HMIWidg…

### PR DESCRIPTION
**Pull request by zenghuan1**
This PR is to create a new project SDL_Qt_HMI.

**Risk**

This PR makes no RPC changes.

**Summary**

The project for HMI development on SDL, and the original SDL project "testSDK" is a submodule of the new project and renamed SDLApps.The current project includes Home, QuickLanuch, and SDLApps.Afterwards, functions modules such as Settings, Phone, and Weather will be added one after another.

**Enhancements**

The new project adds settings, weather, phone and other functional modules to simulate a more complete vehicle system. Add framework to manage various functional modules, optimize code logic, and improve software performance.

### CODE REVIEW

**Comment by BrandonHe** [comment]
@zenghuan1 
Please use the standard workflow to send PR.
Maybe you can reference [here](https://github.com/smartdevicelink/sdl_core/pull/1864)

**Comment by zenghuan1** [comment]
This PR is to adjust the SDLApps directory structure.

**Risk**

This PR makes no RPC changes.

**Summary**

Adjust the SDLApps directory structure, keep the app, Factory Templates, UI directories, other files and directories into the Templates directory. Create a new utils directory in the Templates directory and move the VideoStream directory to utils.

**Enhancements**

Adjust the SDLApps directory structure，can make the engineering structure more standardized.

**Comment by zenghuan1** [comment]
This PR is to add Interface.

**Risk**

This PR makes no RPC changes.

**Summary**

Add gst-based boot animation interface.

**Enhancements**

Gst supports linux platform and can be well embedded in QtHMI project.

**Comment by zenghuan1** [comment]
This PR is to add the settings related child controls to the HMIWidgets directory.

Risk

This PR makes no RPC changes.

Summary

In order to satisfy QtHMI development, the Qt child controls are custom-encapsulated.

Enhancements

Child controls can be expanded and reused again.

**Comment by zenghuan1** [comment]
This PR is to add new features in the QtHMI project.

**Risk**

This PR makes no RPC changes.

**Summary**

Added settings features ，boot animation and statusbar features.

**Enhancements**

New features in the QtHMI project.

**Pull request merged**
